openapi: 3.0.0
info:
  title: Image Analysis API
  version: 1.0.0

paths:
  /analyze:
    post:
      tags:
      - Image Analysis
      summary: Analyze image
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The image file to analyze
      responses:
        200:
          description: Analysis results
          content:
            application/json:
              schema:
                type: object
                properties:
                  prediction:
                    type: string