name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      ethereum:
          image: trufflesuite/ganache-cli:latest
          options: --network-alias localhost -p 8545:8545
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Use a stable Python version

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y libopenblas-dev  # Install OpenBLAS
        pip install pytest pytest-cov  # Install pytest and pytest-cov

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd):$(pwd)/src" >> $GITHUB_ENV
    

    - name: Run tests with coverage
      run: |
        source venv/bin/activate
        pytest --cov=src --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
